### ISSUE TITLE
Fail to parse my gexf file - 

### ISSUE THREAD

**Issue by hpiedcoq** [medialab/graph-recipes#5]
Hi,
Thanks for this great app.

It seems that my gexf file isn't parsed by graph-recipes, under FF or Chrome on OSX (my config).

![](https://framapic.org/bRHepb5VprBQ/3epCKTglqkII)

The file : 
[reseau.gexf.zip](https://github.com/medialab/graph-recipes/files/791196/reseau.gexf.zip)

**Comment by Yomguithereal** [comment]
Quick check: do you have parallel edges?

**Comment by hpiedcoq** [comment]
I don't think so.

Here's the graph visualized with Gephi.

![](https://framapic.org/1GuGVF6DD7Gw/3ObZ5oMeD2Eb)

**Comment by Yomguithereal** [comment]
Ok, your graph is parsed correctly. However it seems it does not have x or y positions which means rendering recipes will fail. Try to apply FA2 layout recipe and then edit the colors of your nodes for instance.

@jacomyma: maybe a simple recipe to perform a random layout and color the nodes could be useful.

Plus, displaying in the left panel whether we have viz attributes or not might be useful?

**Comment by Yomguithereal** [comment]
@hpiedcoq did you export viz attributes when saving your graph to gexf from gephi (I am a Gephi layman but the fact is your gexf file does not have viz attributes)?

**Comment by hpiedcoq** [comment]
Hmmm this graph was made using R so I should check my script I think.

@Yomguithereal doing the FA2 layout recipe did the trick! Thanks!
I'm currently testing others recipes.

**Comment by hpiedcoq** [comment]
OK My graph is pretty poor  so here's a simple viz : 

![](https://framapic.org/p1UDtBHB1Kfq/sKCsJnflGGl0)

Thanks for your support!

**Comment by Yomguithereal** [comment]
Try adding some colors to your node using a custom recipe. Something along:

```js
g.nodes().forEach(node => graph.setNodeAttribute(node, 'color', 'cyan');
```

This should be a little less eerie :)

**Comment by jacomyma** [comment]
Ok so, how to get a diagnostic of this? First you can use the recipe "Attributes Tapas". It gives this output:
```
# Node attributes (1)
label

# Edge attributes (0)
```
This means the x and y positions are not present in the parsed network. Does it come from the parser? A look inside the GEXF file shows that the file does not contain x and y.

```xml
<?xml version="1.0" encoding="UTF-8"?>
(...)
  <graph mode="static" defaultedgetype="directed">
    <nodes>
      <node id="1" label="luis@t-s.fr"/>
      <node id="2" label="eBay@reply.ebay.fr"/>
      <node id="3" label="news@offresdenfer.com"/>
      <node id="4" label="mydesign@bonplan.mydesign.com"/>
(...)
```

As you have identified, your script does not export the coordinates...

You can give positions to nodes with the "Layout Specialty Gravy" recipe. Then the identified missing of color attributes makes it fail. This is on my side, I'll fix it!

**Comment by jacomyma** [comment]
fixed recipes (Note: not yet pushed online right now)

**Comment by jacomyma** [comment]
public website now updated!
